<a href="https://colab.research.google.com/github/Vinay-Yadav01/Learning-ML/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np          #### Importing Numpy Library

# Numpy vs List

Type Difference

In [ ]:
x = numpy.array([1,2,3])
print(x)
print(type(x));

[1 2 3]
<class 'numpy.ndarray'>


In [ ]:
y = [1,2,3]
print(y)
print(type(y))

[1, 2, 3]
<class 'list'>


Time taken

In [ ]:
%timeit [i**3 for i in range(1000)]

474 µs ± 140 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [ ]:
%timeit numpy.arange(1000)**3

5.27 µs ± 178 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


# Create NumPy Array

In [ ]:
y = []
for i in range(5):
    num = int(input("Enter a number: "))
    y.append(num)
print(np.array(y))

Enter a number: 02
Enter a number: 41
Enter a number: 26
Enter a number: 75
Enter a number: 106
[  2  41  26  75 106]


In [ ]:
arr = np.array([[1,2,3,4,5], [4,15,9,1,2]])
print(arr)
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

[[ 1  2  3  4  5]
 [ 4 15  9  1  2]]
2
(2, 5)
10
int64


In [ ]:
arr = np.array([1,2,3,4,5], ndmin=5)
print(arr)
print(arr.ndim)
print(arr.shape)

[[[[[1 2 3 4 5]]]]]
5
(1, 1, 1, 1, 5)


## Special Array

In [ ]:
#Zero Array
arr = np.zeros((2,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
#One Array
arr = np.ones((2,3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
#Empty Array
arr = np.empty((2,3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
#Within a Range
arr = np.arange(2,10)
print(arr)

[2 3 4 5 6 7 8 9]


In [ ]:
#Identity Matrix
arr = np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#If we want array divide in 'num' element with equal interval within a range
arr = np.linspace(1,10,num=7)
print(arr)

[ 1.   2.5  4.   5.5  7.   8.5 10. ]


## NumPy Array with Random Function

In [ ]:
#Rand() --> It generate random number between 0 and 1
arr = np.random.rand(3)
print(arr)

[0.63245229 0.61299174 0.37122544]


In [ ]:
#randn() --> It generate random number closes to 0 either positive or negative
arr = np.random.randn(3,5)
print(arr)

[[ 0.02672077  0.73522372 -0.26673982  2.00499152 -0.39383493]
 [-0.37642201 -0.25279326  1.71812371  0.59127994 -1.47361492]
 [ 0.43922819 -0.50056499  0.69933061  1.41823801  1.00365132]]


In [ ]:
#randf() --> Same as rand() but here 1 is exclusive
arr = np.random.ranf((3,4,5))
print(arr)

[[[0.78224699 0.9578815  0.65303054 0.37831127 0.22935008]
  [0.08441829 0.17033837 0.10084701 0.64797114 0.86162652]
  [0.69108643 0.74982035 0.49535584 0.70929504 0.43811625]
  [0.77842905 0.04381392 0.95414698 0.30486453 0.72959072]]

 [[0.57473673 0.95514498 0.01298938 0.35207711 0.65854418]
  [0.34158468 0.33599457 0.267129   0.65083525 0.78277137]
  [0.25914856 0.7706071  0.06975438 0.58080563 0.93019542]
  [0.12699333 0.91090151 0.90275284 0.78513509 0.68131599]]

 [[0.4797499  0.52059196 0.62613292 0.07834434 0.35172983]
  [0.59847384 0.25074221 0.98734073 0.86531984 0.0683368 ]
  [0.96524021 0.05443338 0.43951509 0.41806263 0.12696675]
  [0.01085441 0.77326853 0.03818337 0.52204105 0.63002955]]]


In [ ]:
#randint() --> It generate random nu,ber between any given range
arr = np.random.randint(1,100,(4,10))
print(arr)

[[ 4 52 79 59 87 95 73 54 60 44]
 [23  7 62 17 54 68 69 82 69 97]
 [88 55  8 83 36  3 93 89 77 13]
 [82 10 46 61 75 15 46  6 47 89]]


# Data Type in Numpy

In [ ]:
arr = np.array([1,2,3,4,5])
print(arr.dtype)

int64


In [ ]:
arr = np.array(['A', 'B', 'C'])
print(arr.dtype)

<U1


In [ ]:
#Changing datatype
arr = np.array([1,2,3,4,5], dtype=np.int8)
print(arr.dtype)

int8


In [ ]:
#Another Way
arr = np.array([1,2,3,4,5], dtype='f')
print(arr.dtype)

float32


In [ ]:
#Similarly
arr = np.float32([1,2,3,4,5])
print(arr.dtype)

float32


In [ ]:
#Another Way
arr = np.array([1,2,3,4,5])
newarr = arr.astype(np.float32) #or arr.astype(float)
print(arr.dtype)
print(newarr.dtype)

int64
float32


# NumPy Arithmetic Operation

## 1-D Array

In [ ]:
#For 1-D Array
arr = np.array([1,2,3,4,5])
print(arr+2)
print(arr-2)
print(arr*2)
print(arr/2)
print(arr%2)

[3 4 5 6 7]
[-1  0  1  2  3]
[ 2  4  6  8 10]
[0.5 1.  1.5 2.  2.5]
[1 0 1 0 1]


In [ ]:
#Similar can be done by their respective function as below
arr = np.array([1,2,3,4,5])
print(np.add(arr,2))
print(np.subtract(arr,2))
print(np.multiply(arr,2))
print(np.divide(arr,2))
print(np.mod(arr,2))
print(np.power(arr,2))
print(np.reciprocal(arr))

[3 4 5 6 7]
[-1  0  1  2  3]
[ 2  4  6  8 10]
[0.5 1.  1.5 2.  2.5]
[1 0 1 0 1]
[ 1  4  9 16 25]
[1 0 0 0 0]


In [ ]:
#For 2 1-D Array
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])
print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2)
print(arr1%arr2)

[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]
[1 2 3 4 5]


In [ ]:
#Similarly their function same as above
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])
print(np.add(arr1,arr2))
print(np.subtract(arr1,arr2))
print(np.multiply(arr1,arr2))
print(np.divide(arr1,arr2))
print(np.mod(arr1,arr2))
print(np.power(arr1,arr2))
print(np.reciprocal(arr1))

[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]
[1 2 3 4 5]
[      1     128    6561  262144 9765625]
[1 0 0 0 0]


## 2-D Array

In [ ]:
arr1 = np.array([[1,2,3,4,5], [6,7,8,9,10]])
arr2 = np.array([[11,12,13,14,15], [16,17,18,19,20]])
print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2)
print(arr1%arr2)

[[12 14 16 18 20]
 [22 24 26 28 30]]
[[-10 -10 -10 -10 -10]
 [-10 -10 -10 -10 -10]]
[[ 11  24  39  56  75]
 [ 96 119 144 171 200]]
[[0.09090909 0.16666667 0.23076923 0.28571429 0.33333333]
 [0.375      0.41176471 0.44444444 0.47368421 0.5       ]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


## More Arithmetic Function of NumPy

### 1-D Array

In [ ]:
arr = np.array([1,2,3,4,5])
print(np.min(arr))
print(np.max(arr))
print(np.argmin(arr))
print(np.argmax(arr))
print(np.sqrt(arr))
print(np.cumsum(arr))

1
5
0
4
[1.         1.41421356 1.73205081 2.         2.23606798]
[ 1  3  6 10 15]


In [ ]:
arr = np.array([1,2,3,4,5])
print(np.sin(arr))
print(np.cos(arr))
print(np.tan(arr))


[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]
[ 1.55740772 -2.18503986 -0.14254654  1.15782128 -3.38051501]


### 2-D Array

In [ ]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(np.min(arr))
print(np.max(arr))
print(np.argmin(arr))
print(np.argmax(arr))
print(np.sqrt(arr))

1
10
0
9
[[1.         1.41421356 1.73205081 2.         2.23606798]
 [2.44948974 2.64575131 2.82842712 3.         3.16227766]]


Means if we pass any n array it will internally take it as 1-D

But if we want to take them along every row of every col or any dimension, we have to pass axis value

In [ ]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

#axis = 0 --> means col wise
#axis = 1 --> means row wise

print(np.min(arr, axis=0))
print(np.max(arr, axis=0))
print(np.argmin(arr, axis=0))
print(np.argmax(arr, axis=0))
print(np.sqrt(arr))

print(np.min(arr, axis=1))
print(np.max(arr, axis=1))
print(np.argmin(arr, axis=1))
print(np.argmax(arr, axis=1))
print(np.sqrt(arr))

[1 2 3 4 5]
[ 6  7  8  9 10]
[0 0 0 0 0]
[1 1 1 1 1]
[[1.         1.41421356 1.73205081 2.         2.23606798]
 [2.44948974 2.64575131 2.82842712 3.         3.16227766]]
[1 6]
[ 5 10]
[0 0]
[4 4]
[[1.         1.41421356 1.73205081 2.         2.23606798]
 [2.44948974 2.64575131 2.82842712 3.         3.16227766]]


# Shape and Reshape


In [ ]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10], [11,12,13,14,15],[16,17,18,19,20]])
print(arr.shape)
arr.reshape(5,2,2)
# arr.reshape(-1)

(4, 5)


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

# Broadcasting

In [ ]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([1,2,3])
# arr1+arr2  #Generate error of broadcasting
arr2 = np.array([[1],[2],[3]])
print(arr1+arr2)   #Work Fine

[[2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]]


# Indexing and Slicing

## Indexing

In [ ]:
arr = np.array([1,2,3,4])
#Indexing       0,1,2,3
#              -4,-3,-2,-1
print(arr[0])
print(arr[-1])

1
4


In [ ]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr[0,1])
print(arr[1,-1])

2
8


## Slicing

In [ ]:
arr = np.array([1,2,3,4,5,6,7])
#Indexing       0,1,2,3,4,5,6
print(arr[1:5])
print(arr[4:])
print(arr[:4])
print(arr[-3:-1])
print(arr[1:5:2])

[2 3 4 5]
[5 6 7]
[1 2 3 4]
[5 6]
[2 4]


In [ ]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr[1, 1:4])
print(arr[0:2, 2])

[7 8 9]
[3 8]


# Iterating

In [ ]:
arr = np.array([1,2,3,4])
for i in arr:
  print(i)

1
2
3
4


In [ ]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
for i in arr:
  print(i)

[1 2 3 4]
[5 6 7 8]


In [ ]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
for i in arr:
  for j in i:
    print(j)

1
2
3
4
5
6
7
8


In [ ]:
arr = np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]]) #Corrected the array definition to create a 3D array
for i in arr:
  for j in i:
    for k in j:
      print(k)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16


In [ ]:
#Function for iterating multiple loops
arr = np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]]) #Corrected the array definition to create a 3D array
# for i in np.nditer(arr):
#   print(i)

#Using buffer to change its type ans store it in buffer
# for i in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
#   print(i)

#Printing with indexing too
for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 0, 3) 4
(0, 1, 0) 5
(0, 1, 1) 6
(0, 1, 2) 7
(0, 1, 3) 8
(1, 0, 0) 9
(1, 0, 1) 10
(1, 0, 2) 11
(1, 0, 3) 12
(1, 1, 0) 13
(1, 1, 1) 14
(1, 1, 2) 15
(1, 1, 3) 16


# Copy and View Function

In [ ]:
arr = np.array([1,2,3,4])
print(arr)
copy_arr = arr.copy()
print(copy_arr)

[1 2 3 4]
[1 2 3 4]


In [ ]:
arr = np.array([1,2,3,4])
print(arr)
view_arr = arr.view()
print(view_arr)

Although they looks same but they perform different task, as in **copy**, we make a copy of oeiginal array therefore any changes in copy array will not reflect in original array but in **view**, it actually pointing to same in array therefore any changes will reflect in original array too.

# Joining and Split

## Joining Function

In [40]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
# arr = np.concatenate((arr1, arr2))
# print(arr)

#Using Stack Function
arr = np.stack((arr1, arr2), axis=1)
print(arr)

[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [39]:
arr1 = np.array([[1,2,3,4],[5,6,7,8]])
arr2 = np.array([[9,10,11,12],[13,14,15,16]])
# arr = np.concatenate((arr1, arr2), axis=1) #Along Row
# print(arr)


#Using Stack Function
arr = np.stack((arr1, arr2), axis=1)
print(arr)

[[[ 1  2  3  4]
  [ 9 10 11 12]]

 [[ 5  6  7  8]
  [13 14 15 16]]]


In [41]:
#Diferent types of stack function

arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
arr = np.stack((arr1, arr2), axis=1)
print(arr)
arr = np.hstack((arr1, arr2))
print(arr)
arr = np.vstack((arr1, arr2))
print(arr)
arr = np.dstack((arr1, arr2))
print(arr)

[[1 5]
 [2 6]
 [3 7]
 [4 8]]
[1 2 3 4 5 6 7 8]
[[1 2 3 4]
 [5 6 7 8]]
[[[1 5]
  [2 6]
  [3 7]
  [4 8]]]


## Spliting Function

In [43]:
arr = np.array([1,2,3,4,5,6])
newarr = np.array_split(arr, 3)
print(newarr) #List of Array
#Individual Array
for i in newarr:
  print(i)

[array([1, 2]), array([3, 4]), array([5, 6])]
[1 2]
[3 4]
[5 6]


In [44]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
newarr = np.array_split(arr, 3)
print(newarr) #List of Array
#Individual Array
for i in newarr:
  print(i)

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]]), array([], shape=(0, 4), dtype=int64)]
[[1 2 3 4]]
[[5 6 7 8]]
[]


# Search, Sort, Filter

In [45]:
arr = np.array([1,2,3,4,5,4,4])
x = np.where(arr == 4)
print(x)

(array([3, 5, 6]),)


In [47]:
arr = np.array([1,2,3,4,5,4,4])
x = np.searchsorted(arr, 4)
print(x)
y = np.searchsorted(arr, 4, side='right')
print(y)
z = np.searchsorted(arr, [2,4,6])
print(z)

3
7
[1 3 7]


In [49]:
arr = np.array([1,2,3,4,5,4,4])
print(np.sort(arr))

#Also work for strings

arr = np.array(['B', 'A', 'C'])
print(np.sort(arr))

[1 2 3 4 4 4 5]
['A' 'B' 'C']


In [51]:
#For 2-D array
arr = np.array([[3,2,4],[5,0,1]])
print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


In [52]:
#Filter Function

arr = np.array([41,42,43,44])
x = [True, False, True, False]
newarr = arr[x]
print(newarr)

[41 43]


In [54]:
#Shuffle
arr = np.array([1,2,3,4,5])
np.random.shuffle(arr)
print(arr)

[4 1 5 3 2]


In [58]:
#Unique
arr = np.array([1,2,3,4,5,4,4])
print(np.unique(arr))
print(np.unique(arr, return_index=True))
print(np.unique(arr, return_counts=True))

[1 2 3 4 5]
(array([1, 2, 3, 4, 5]), array([0, 1, 2, 3, 4]))
(array([1, 2, 3, 4, 5]), array([1, 1, 1, 3, 1]))


In [59]:
#Resize
arr = np.array([1,2,3,4,5,6,7,8])
newarr = np.resize(arr, (3,3))
print(newarr)

[[1 2 3]
 [4 5 6]
 [7 8 1]]


In [64]:
#Flatten
arr = np.array([[1,2,3,4],[5,6,7,8]])
newarr = arr.flatten()
print(newarr)
newarr = arr.flatten(order='F')
print(newarr)

[1 2 3 4 5 6 7 8]
[1 5 2 6 3 7 4 8]


In [65]:
#Ravel
arr = np.array([[1,2,3,4],[5,6,7,8]])
newarr = arr.ravel()
print(newarr)
newarr = arr.ravel(order='F')
print(newarr)

[1 2 3 4 5 6 7 8]
[1 5 2 6 3 7 4 8]


# Insert and Delete

In [70]:
arr = np.array([1,2,3,4])
# print(np.insert(arr, 2, 10))
print(np.append(arr,10))

[ 1  2  3  4 10]


In [67]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(np.insert(arr, 2, 10, axis=0))
print(np.insert(arr, 2, 10, axis=1))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [10 10 10 10]]
[[ 1  2 10  3  4]
 [ 5  6 10  7  8]]


In [68]:
arr = np.array([1,2,3,4])
print(np.delete(arr, 2))

[1 2 4]


In [71]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(np.delete(arr, 1, axis=0))
print(np.delete(arr, 1, axis=1))

[[1 2 3 4]]
[[1 3 4]
 [5 7 8]]


# Matrix Multiplication

In [74]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr)
print(type(arr))
print(arr.shape)

[[1 2 3 4]
 [5 6 7 8]]
<class 'numpy.ndarray'>
(2, 4)


In [73]:
mat = np.matrix(arr)
print(mat)
print(type(mat))
print(mat.shape)

[[1 2 3 4]
 [5 6 7 8]]
<class 'numpy.matrix'>
(2, 4)


In [77]:
mat1 = np.matrix([[1,2,3,4],[5,6,7,8]])
mat2 = np.matrix([[1,2,3,4],[5,6,7,8]])
print(mat1+mat2)
print(mat1-mat2)

[[ 2  4  6  8]
 [10 12 14 16]]
[[0 0 0 0]
 [0 0 0 0]]


In [82]:
mat1 = np.matrix([[1,2,3],[5,6,7],[4,6,8]])
mat2 = np.matrix([[1,2,3],[5,6,7],[9,2,7]])
print(mat1*mat2)
print(mat1@mat2)
print(np.dot(mat1, mat2))

[[ 38  20  38]
 [ 98  60 106]
 [106  60 110]]
[[ 38  20  38]
 [ 98  60 106]
 [106  60 110]]
[[ 38  20  38]
 [ 98  60 106]
 [106  60 110]]


In [83]:
mat = np.matrix([[1,2,3,4],[5,6,7,8]])

#Transpose
print(mat.T)

#Diagonal
print(mat.diagonal())

#Flatten
print(mat.flatten())

#Min
print(mat.min())

#Max
print(mat.max())

#Sum
print(mat.sum())

#Standard Deviation
print(mat.std())



[[1 5]
 [2 6]
 [3 7]
 [4 8]]
[[1 6]]
[[1 2 3 4 5 6 7 8]]
1
8
36
2.29128784747792


In [98]:
mat = np.matrix([[1,2],[5,6]])

#Swapaxes
print(mat.swapaxes(0,1))

#Determinant
print(np.linalg.det(mat))

#Inverse
print(mat.I)


[[1 5]
 [2 6]]
-3.999999999999999
[[-1.5   0.5 ]
 [ 1.25 -0.25]]


In [95]:
#Power
mat = np.matrix([[1,2],[5,6]])

#For n=0, it is Identiy matrix
print(np.linalg.matrix_power(mat, 0))

#For n>1, it is Power of matrix
print(np.linalg.matrix_power(mat, 2))

#For n<0, it is multiplication of Inverse of matrix and Power of the matrix
print(np.linalg.matrix_power(mat, -2))


[[1 0]
 [0 1]]
[[11 14]
 [35 46]]
[[ 2.875  -0.875 ]
 [-2.1875  0.6875]]
